---
- name: OpenSSHd - Copy sshd configuration block
  ansible.builtin.template:
    src: ZZ_sshd_config.conf.j2
    dest: /etc/ssh/sshd_config.d/ZZ_sshd_config.conf
  notify: Restart sshd

- name: OpenSSHd - Include configuration block
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    line: "Include /etc/ssh/sshd_config.d/*.conf"
    insertafter: EOF
  notify:
    - Restart sshd

- name: OpenSSHd - Start and enable sshd
  ansible.builtin.systemd:
    name: sshd
    enabled: yes
    state: started
    masked: no
